version: '2'
services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"